composer/urls.py
from django.urls import path

from . import views

app_name = 'composer'

urlpatterns = [
    path('', views.index, name='index'),
    path('download/', views.download, name='download'),
    path('produce/', views.produce, name='produce'),
    path('upload/', views.user_upload, name='upload'),
    path('team/', views.team, name='team'),
    path('learn/', views.learn, name='learn'),
    path('sheet/', views.download_sheet, name='sheet'),
    path('comparison/', views.comparison, name='comparison'),
]

musicComposer/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
	path('cmp/', include('composer.urls')),
    path('admin/', admin.site.urls),

]

composer/models.py
from django.db import models

# Create your models here.

composer/forms.py
from django import forms


class UploadFileForm(forms.Form):
	
	file = forms.FileField(widget=forms.FileInput(attrs={'class' : 'form-control btn btn-outline-secondary','style':'height:45px'}))
    

composer/views.py
import os
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from wsgiref.util import FileWrapper
from .forms import UploadFileForm



# Create your views here.

def handle_uploaded_file(f):
    with open('composer/media/composer/userUpload/userUpload.mid', 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)


def index(request):

	form = UploadFileForm()
	return render(request, 'composer/index.html', {'form': form})


	# if request.method == 'POST':
	# 	form = UploadFileForm(request.POST, request.FILES)
	# 	if form.is_valid():
	# 		handle_uploaded_file(request.FILES['file'])
	# 		# os.system("python composer/user_produce.py")
	# 		return HttpResponseRedirect('upload/')
	# else:
	# 	form = UploadFileForm()
	# return render(request, 'composer/index.html', {'form': form})


def user_upload(request):

	if request.method == 'POST':
		form = UploadFileForm(request.POST, request.FILES)
		if form.is_valid():
			handle_uploaded_file(request.FILES['file'])
			os.system("python composer/user_produce.py")
			formT=UploadFileForm()
			return render(request, 'composer/upload.html', {'form': formT})
	else:
		form = UploadFileForm()
	return render(request, 'composer/upload.html', {'form': form})


def produce(request):

	form = UploadFileForm()
	os.system("python composer/Produce.py")
	return render(request, 'composer/produce.html', {'form': form})

	# if request.method == 'POST':
	# 	form = UploadFileForm(request.POST, request.FILES)
	# 	if form.is_valid():
	# 		handle_uploaded_file(request.FILES['file'])
	# 		os.system("python composer/user_produce.py")
	# 		formT=UploadFileForm()
	# 		return render(request, 'composer/upload.html', {'form': formT})
	# 		return user_upload(request)
	# else:
		
	# 	form = UploadFileForm()
	# 	os.system("python composer/Produce.py")
	# return render(request, 'composer/produce.html', {'form': form})





def download(request):

	file_path="composer/static/composer/output/output.mid"

	with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="audio/mid")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            return response


def download_sheet(request):

	file_path="composer/static/composer/musicSheets/musicxml.xml"

	with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="audio/mid")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            return response

	
def team(request):

	return render(request,'composer/team.html')


def learn(request):

	return render(request,'composer/learn.html')



def comparison(request):

	return render(request,'composer/comparison.html')
	

composer/templates/composer/base.html
{% load static %}



<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>Music Composer</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


	<link href="{% static "composer/CSS/PerMu.css" %}" rel="stylesheet">

</head>
<body class="text-center" style="background-color:#eaecef;">

	<div class="container">

		<nav class="navbar navbar-dark bg-dark navbar-expand-md navbar-expand-lg">
			<a class="navbar-brand" href="#">PerMu</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="collapsibleNavbar">
				<ul class="navbar-nav">
					<li class="nav-item active">
						<a class="nav-link" href="{% url 'composer:index' %}">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'composer:team' %}">Team</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'composer:comparison' %}" target="_blank">Compare</a>
					</li>

				</ul>
			</div>
		</nav>

		

		{% block content %}


		{% endblock %}

		

	</div>

</body>
<!-- Latest compiled and minified JavaScript -->
<script type="text/javascript">
	(function (d) {
		for (var i = 0; i < 2; i++) {
			d.getElementsByClassName("generateForm")[i].onsubmit = function () {
    d.getElementById("disappear").style.display = 'none';
    d.getElementById("loading").style.display = 'block';
		}
  };
}(document));
</script>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>


</html>

composer/templates/composer/index.html
{% extends 'composer/base.html' %}

{% load static %}

{% block content %}


<div class="jumbotron" style="background-color:#3b3b3f;color: white;margin-top: 10px;opacity: 0.9">
	<h1 class="display-4">Let's Create Music</h1>
	<p class="lead">PerMu is a one-page tool for building simple and beautiful piano compositions. Create a random composition or Create using your own sample.</p>
	<hr class="my-3" style="border-color: white">
	<p class="lead">
		<a href="{% url 'composer:learn' %}" class="btn btn-lg btn-primary">Learn more</a>
	</p>
</div>


<!-- Loading Icon -->
<div id="loading" style="display:none;">
	<img src="{% static 'composer/images/loader.gif' %}" alt="" />
	<h4>Generating music</h4>
</div>

<!-- Part that disappears on loading -->
<div id="disappear">
	<div class="row">
		<div class="col">
			<form action="{% url 'composer:produce' %}" method="post" class="generateForm">

				{% csrf_token %}
				<p class="lead">
					<input type="submit" name="produce" value="Compose Randomly" data-toggle="popover" title="generate music" data-placement="right" class="btn btn-lg btn-primary">
				</p>
			</form>	
		</div>
	</div>


	<div class="row">

		<div class="col">

			<h3>OR</h3>

		</div>
	</div>


	<div class ="row">
		<div class="col" >
			<form method="post" enctype="multipart/form-data" action="{% url 'composer:upload' %}" class="generateForm">
				{% csrf_token %}
				<div class="form-group">
					{{ form.file }}
				</div>
				<div class="form-group">
					<button type="submit" class="btn btn-primary btn-lg">Upload</button>

				</div>

			</form>

		</div>
	</div>


</div>


<!-- <script type="text/javascript">
	(function (d) {
		for (var i = 0; i < 2; i++) {
			d.getElementsByClassName("generateForm")[i].onsubmit = function () {
    d.getElementById("disappear").style.display = 'none';
    d.getElementById("loading").style.display = 'block';
		}
  };
}(document));
</script> -->


{% endblock %}

composer/templates/composer/learn.html
{% extends 'composer/base.html' %}

{% load static %}
{% block content %}

<div class="jumbotron" style="background-color:#3b3b3f;color: white;margin-top: 10px;opacity: 0.9">
	<h1 class="display-4">Let's Create Music</h1>
	<p class="lead">PerMu is a one-page tool for building simple and beautiful piano compositions. Create a random composition or Create using your own sample.</p>
	<hr class="my-2" style="border-color: white">
</div>


<div class="row">
	<div class="col">
		<nav id="navbar-example3" class="navbar navbar-dark flex-column">
			<a class="nav-link" href="#item-1">Introduction</a>
			<a class="nav-link" href="#item-2">Recurrent Neural Networks</a>
			<a class="nav-link" href="#item-3">Music21</a>
			<a class="nav-link" href="#item-4">Keras</a>
			<a class="nav-link" href="#item-5">Data</a>

		</nav>
	</div>

	<div data-spy="scroll" data-target="#navbar-example3" data-offset="0" style="height:250px;overflow-y: scroll;position: relative;" class="col">
		<h4 id="item-1">Introduction</h4>
		<p>Neural networks are being used to improve all aspects of our lives. They provide us with recommendations for items we want to purchase, generate text based on the style of an author and can even be used to change the art style of an image. In recent years, there have been a number of projects on how to generate text using neural networks but a lack of projects on how to create music. In this project we went through how to create music using a recurrent neural network in Python using the Keras library.

		</p>
		<h4 id="item-2">Recurrent Neural Network</h4>
		<p>A recurrent neural network is a class of artificial neural networks that make use of sequential information. They are called recurrent because they perform the same function for every single element of a sequence, with the result being dependent on previous computations. Whereas outputs are independent of previous computations in traditional neural networks.

			In this project we used a BiDirectional Long Short-Term Memory (LSTM) network. They are a type of Recurrent Neural Network that can efficiently learn via gradient descent. Using a gating mechanism, LSTMs are able to recognise and encode long-term patterns. LSTMs are extremely useful to solve problems where the network has to remember information for a long period of time as is the case in music and text generation.

		</p>
		<h4 id="item-3">Music21</h4>
		<p>Music21 is a Python toolkit used for computer-aided musicology. It allows us to teach the fundamentals of music theory, generate music examples and study music. The toolkit provides a simple interface to acquire the musical notation of MIDI files. Additionally, it allows us to create Note and Chord objects so that we can make our own MIDI files easily.

		</p>
		<h4 id="item-4">Keras</h4>
		<p>Keras is a high-level neural networks API that simplifies interactions with Tensorflow. It was developed with a focus on enabling fast experimentation.

		In this project we used the Keras library to create and train the BiDirectional LSTM model. Once the model was trained we used it to generate the musical notation for our music.</p>


	</p>
	<h4 id="item-5">Data</h4>
	<p>we used piano music, mostly consisting of music from Final Fantasy soundtracks. We picked Final Fantasy music due to the very distinct and beautiful melodies that the majority of the pieces have and the sheer amount of pieces that exist. But any set of MIDI files consisting of a single instrument would work for our purposes.	</p>
</div>
</div>



{% endblock %}

composer/templates/composer/load.html
	ssssssss

composer/templates/composer/produce.html
{% extends 'composer/base.html' %}
{% load static %}

{% block content %}


<div class="jumbotron" style="background-color:#3b3b3f;color: white;margin-top: 10px;opacity: 0.9">
	<h1 class="display-4">Let's Create Music</h1>
	<p class="lead">PerMu is a one-page tool for building simple and beautiful piano compositions. Create a random composition or Create using your own sample.</p>
	<hr class="my-3" style="border-color: white">
	<p class="lead">
		<a href="{% url 'composer:learn' %}" class="btn btn-lg btn-primary">Learn more</a>
	</p>
</div>

<!-- Loading Icon -->
<div id="loading" style="display:none;">
	<img src="{% static 'composer/images/loader.gif' %}" alt="" />
	<h4>Generating music</h4>
</div>


<!-- Part that disappears on loading -->
<div id="disappear">
	<div class="row">
		<div class="col">
			<form action="{% url 'composer:produce' %}" method="post" class="generateForm">

				{% csrf_token %}
				<p class="lead">
					<input type="submit" name="produce" value="Compose Randomly" data-toggle="popover" title="generate music" data-placement="right" class="btn btn-lg btn-primary">
				</p>
			</form>	
		</div>
	</div>


	<div class="row">

		<div class="col">

			<h3>OR</h3>

		</div>
	</div>



	<div class ="row">
		<div class="col">
			<form method="post" enctype="multipart/form-data" action="{% url 'composer:upload' %}" class="generateForm">
				{% csrf_token %}
				<div class="form-group">
					{{ form.file }}
				</div>

				<div class="form-group">
					<button type="submit" class="btn btn-primary btn-lg">Upload</button>

				</div>

			</form>

		</div>
	</div>




		<div class="row">

			<div class="col">

				<h3>Music Ready</h3>

			</div>
		</div>



		<div class="row">
			<div class="col-md-4" style="float: left">

				<form action="{% url 'composer:download' %}" method="post">

					{% csrf_token %}
					<p class="lead">
						<input type="submit" name="download" value="MIDI" class="btn btn-lg btn-outline-secondary">
					</p>
				</form>	

			</div>

			<div class="col-md-4" style="float: left">

				<form action="{% url 'composer:sheet' %}" method="post">

					{% csrf_token %}
					<p class="lead">
						<input type="submit" name="sheet" value="Sheet" class="btn btn-lg btn-outline-secondary">
					</p>
				</form>	

			</div>

			<div class="col-md-4" style="float: left">
				<audio controls="controls">
					<source src="{% static 'composer/output/play.mp3' %}" type="audio/mpeg">
						Your browser does not support the audio element.
					</audio>
				</div>

			</div>

		</div>

	</div>



	{% endblock %}

composer/templates/composer/team.html
{% extends 'composer/base.html' %}

{% load static %}
{% block content %}

<div class="jumbotron" style="background-color:#3b3b3f;color: white;margin-top: 10px;opacity: 0.9">
	<h1 class="display-4">Our Team</h1>
	<p class="lead">PerMu is created by following students</p>
	<hr class="my-3" style="border-color: white">
	<p class="lead">
		<a href="{% url 'composer:learn' %}" class="btn btn-lg btn-primary">Learn more</a>
	</p>
</div>


<div class="row">
	<div class="col">
		<div class="card">
			<img src = "{% static "composer/images/dev.png" %}" alt="Avatar" style="width:100%">
			<div class="container">
				<h4><b>Gyan Vardhan</b></h4> 
				<p>03014802715</p> 
			</div>
		</div>
	</div>
	<div class="col">
		<div class="card">
			<img src="{% static 'composer/images/dev.png' %}" alt="Avatar" style="width:100%">
			<div class="container">
				<h4><b>Aakash Chawla</b></h4> 
				<p>00114802715</p> 
			</div>
		</div>
	</div>
	<div class="col">
		<div class="card">
			<img src="{% static 'composer/images/dev.png' %}" alt="Avatar" style="width:100%">
			<div class="container">
				<h4><b>Diwanshu Garg</b></h4> 
				<p>02814802715</p> 
			</div>
		</div>
	</div>
</div>


{% endblock %}

composer/templates/composer/upload.html
{% extends 'composer/base.html' %}

{% load static %}
{% block content %}

<div class="jumbotron" style="background-color:#3b3b3f;color: white;margin-top: 10px;opacity: 0.9">
	<h1 class="display-4">Let's Create Music</h1>
	<p class="lead">PerMu is a one-page tool for building simple and beautiful piano compositions. Create a random composition or Create using your own sample.</p>
	<hr class="my-3" style="border-color: white">
	<p class="lead">
		<a href="{% url 'composer:learn' %}" class="btn btn-lg btn-primary">Learn more</a>
	</p>
</div>


<!-- Loading Icon -->
<div id="loading" style="display:none;">
	<img src="{% static 'composer/images/loader.gif' %}" alt="" />
	<h4>Generating music</h4>
</div>


<!-- Part that disappears on loading -->
<div id="disappear">

	<div class="row">
		<div class="col">
			<form action="{% url 'composer:produce' %}" method="post" class="generateForm">

				{% csrf_token %}
				<p class="lead">
					<input type="submit" name="produce" value="Compose Randomly" data-toggle="popover" title="generate music" data-placement="right" class="btn btn-lg btn-primary">
				</p>
			</form>	
		</div>
	</div>


	<div class="row">

		<div class="col">

			<h3>OR</h3>

		</div>
	</div>


	<div class ="row">
		<div class="col">
			<form method="post" enctype="multipart/form-data" action="{% url 'composer:upload' %}" class="generateForm">
				{% csrf_token %}
				<div class="form-group">
					{{ form.file }}
				</div>

				<div class="form-group">
					<button type="submit" class="btn btn-primary btn-lg">Upload</button>

				</div>

			</form>

		</div>
	</div>



	<div class="row">

		<div class="col">

			<h3>Music Ready</h3>

		</div>
	</div>


	<div class="row">
		<div class="col-md-4">

			<form action="{% url 'composer:download' %}" method="post">

				{% csrf_token %}
				<p class="lead">
					<input type="submit" name="download" value="MIDI" class="btn btn-lg btn-outline-secondary">
				</p>
			</form>	

		</div>

		<div class="col-md-4">

			<form action="{% url 'composer:sheet' %}" method="post">

				{% csrf_token %}
				<p class="lead">
					<input type="submit" name="sheet" value="Sheet" class="btn btn-lg btn-outline-secondary">
				</p>
			</form>	

		</div>

		<div class="col-md-4">
			<audio controls>
				<source src="{% static 'composer/output/play.mp3' %}" type="audio/mpeg">
					Your browser does not support the audio element.
				</audio>
			</div>

		</div>


	</div>


	{% endblock %}